---
- name: Installer et configurer le conteneur
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true

  tasks:

    - name: Charger les variables
      include_vars:
        file: jira.yml
      tags: variables

    - name: Import PostgreSQL GPG key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 7FCC7D46ACCC4CF8
        state: present

    - name: Ajouter le référentiel PostgreSQL
      become: yes
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
      register: apt_repository_result

    - name: Importer la clé GPG pour le référentiel PostgreSQL
      become: yes
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
      when: apt_repository_result.changed

    - name: Mettre à jour la liste des paquets
      become: yes
      apt:
        update_cache: yes

    - name: Installer PostgreSQL {{ psql_version }} et les dépendances
      apt:
        name:
          - postgresql-{{ psql_version }}
          #- postgresql-client-{{ psql_version }}
          #- postgresql-contrib-{{ psql_version }}
        state: present

    - name: Activez le service PostgreSQL au démarrage
      service:
        name: postgresql
        enabled: yes
        state: started

    - name: Installer SSH
      apt:
        name: openssh-server
        state: present

    - name: Activez le service SSH au démarrage
      service:
        name: ssh
        enabled: yes
        state: started

    - name: Installer Apache
      package:
        name: apache2  # Pour les distributions basées sur Debian (comme Ubuntu)
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Activez le service Apache au démarrage
      service:
        name: apache2
        enabled: yes
        state: started
